FROM ubuntu:24.04

# 基础环境配置
ENV LANG="en_US.UTF-8" \
    TZ="Asia/Shanghai" \
    APT_MIRROR="http://mirrors.aliyun.com"

# 安装中文字体
COPY ./fonts/simsun.ttc /usr/share/fonts/

# 配置阿里云镜像源、时区
RUN sed -i "s@http://archive.ubuntu.com@${APT_MIRROR}@g" /etc/apt/sources.list.d/ubuntu.sources \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && mkdir -p /app

# 4. 安装基础工具（合并 RUN 减少层数）
RUN apt-get update --fix-missing -o Acquire::http::No-Cache=True \
    && apt-get install -y --no-install-recommends curl wget iproute2 fontconfig tzdata \
    && fc-cache -f -v \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 安装 JDK 8
# COPY jdk-8u192-linux-x64.tar.gz /tmp/
WORKDIR /tmp
RUN curl -O https://repo.huaweicloud.com/java/jdk/8u192-b12/jdk-8u192-linux-x64.tar.gz \
    && tar -xf jdk-8u192-linux-x64.tar.gz -C /usr/local/ \
    && rm -f jdk-8u192-linux-x64.tar.gz \
    && ln -s /usr/local/jdk1.8.0_192 /usr/local/jdk

# 6. 环境变量配置
ENV JAVA_HOME=/usr/local/jdk
ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar \
    PATH=$JAVA_HOME/bin:$PATH \
    JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=75.0 -XX:MinRAMPercentage=75.0"

# 7. 工作目录和启动命令
WORKDIR /app
#CMD ["java", "-jar", "spring.jar"]