FROM centos:centos7.9.2009
LABEL EMAIL="shaopenghk@qq.com"
ENV TOMCAT_VERSION="apache-tomcat-8.5.100"
ENV TZ="Asia/Shanghai"
ENV LC_ALL="en_US.UTF-8"

COPY ./fonts/simsun.ttc /usr/share/fonts/simsun.ttc

RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo \
    && curl -o /etc/yum.repos.d/epel-7.repo https://mirrors.aliyun.com/repo/epel-7.repo \
    && sed -i -e '/mirrors.cloud.aliyuncs.com/d' -e '/mirrors.aliyuncs.com/d' /etc/yum.repos.d/CentOS-Base.repo \
    && yum -y install kde-l10n-Chinese iproute fontconfig \
    && yum -y reinstall glibc-common \
    && yum clean all \ 
    && localedef -c -f UTF-8 -i zh_CN zh_CN.utf8 \
    && fc-list

# COPY ./jdk-8u202-linux-x64.tar.gz /tmp
WORKDIR /tmp
RUN curl -O https://repo.huaweicloud.com/java/jdk/8u202-b08/jdk-8u202-linux-x64.tar.gz \
    && tar -xf jdk-8u202-linux-x64.tar.gz -C /usr/local/ \
    && rm -rf jdk-8u202-linux-x64.tar.gz

ENV JAVA_HOME=/usr/local/jdk1.8.0_202
ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH=$JAVA_HOME/bin:$PATH

RUN curl -O https://mirrors.huaweicloud.com/apache/tomcat/tomcat-8/v8.5.100/bin/${TOMCAT_VERSION}.tar.gz \
    && tar -xf ${TOMCAT_VERSION}.tar.gz -C /usr/local/ \
    && ln -sf /usr/local/${TOMCAT_VERSION} /usr/local/tomcat \ 
    && rm -rf ${TOMCAT_VERSION}.tar.gz \
    && rm -rf /usr/local/${TOMCAT_VERSION}/webapps/*

WORKDIR /usr/local/tomcat/webapps

ENV  JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=75.0 -XX:MinRAMPercentage=75.0"
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]